steps:
  - imports:
      align: global
      pad_module_names: false
  - language_pragmas:
      align: false
  - trailing_whitespace: {}
language_extensions:
  - MultiParamTypeClasses  # workaround
